# Generated by Django 3.2.25 on 2024-06-20 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_project_default_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='font',
            field=models.CharField(choices=[('Arial', 'Arial'), ('Times New Roman', 'Times New Roman'), ('Courier New', 'Courier New'), ('Georgia', 'Georgia'), ('Verdana', 'Verdana')], default='Arial', max_length=50),
        ),
        migrations.AddField(
            model_name='projectelement',
            name='font',
            field=models.CharField(choices=[('Arial', 'Arial'), ('Times New Roman', 'Times New Roman'), ('Courier New', 'Courier New'), ('Georgia', 'Georgia'), ('Verdana', 'Verdana')], default='Arial', max_length=50),
        ),
    ]
