# Generated by Django 3.2.25 on 2024-06-20 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20240620_0916'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
                ('content', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='about_images/')),
                ('order', models.PositiveIntegerField()),
                ('font', models.CharField(choices=[('Arial', 'Arial'), ('Times New Roman', 'Times New Roman'), ('Courier New', 'Courier New'), ('Georgia', 'Georgia'), ('Verdana', 'Verdana')], default='Arial', max_length=50)),
                ('font_size', models.PositiveIntegerField(default=14)),
                ('align', models.CharField(choices=[('left', 'Left'), ('right', 'Right'), ('center', 'Center')], default='left', max_length=10)),
                ('position', models.CharField(choices=[('left', 'Left'), ('right', 'Right'), ('top', 'Top'), ('bottom', 'Bottom')], default='left', max_length=10)),
            ],
        ),
    ]
